# Generated by Django 4.1.3 on 2022-11-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chipuser',
            name='name',
        ),
        migrations.AlterField(
            model_name='chipuser',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
