# Generated by Django 4.1 on 2022-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verb", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="chips/")),
                ("submitted", models.DateTimeField()),
            ],
            options={
                "ordering": ["submitted"],
            },
        ),
    ]
