# Generated by Django 4.1 on 2022-08-09 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chips", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chip",
            options={"ordering": ["timeSubmitted"]},
        ),
        migrations.RenameField(
            model_name="chip",
            old_name="submitted",
            new_name="timeSubmitted",
        ),
    ]
