# Generated by Django 4.1 on 2022-08-09 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chips", "0002_alter_chip_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chip",
            name="photo",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
