# Generated by Django 4.1.3 on 2022-11-25 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0002_goal_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='creator',
        ),
    ]
